// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYXoem83__MCwI1rCBe2vzDU2FzpoUYio',
    appId: '1:492985332872:web:381dab6e5a3f0cdc9a9b3d',
    messagingSenderId: '492985332872',
    projectId: 'flutter-maps-1fd2a',
    authDomain: 'flutter-maps-1fd2a.firebaseapp.com',
    storageBucket: 'flutter-maps-1fd2a.appspot.com',
    measurementId: 'G-PG0XFCCQ2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLi4jXFjrbQhOyefE8aMCVYTqRHl2Cbbw',
    appId: '1:492985332872:android:633e20c38c69a83e9a9b3d',
    messagingSenderId: '492985332872',
    projectId: 'flutter-maps-1fd2a',
    storageBucket: 'flutter-maps-1fd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1YdjMzbn9kEehV23nOHPlGz6nqRBLFhw',
    appId: '1:492985332872:ios:459d77474d5d804e9a9b3d',
    messagingSenderId: '492985332872',
    projectId: 'flutter-maps-1fd2a',
    storageBucket: 'flutter-maps-1fd2a.appspot.com',
    iosClientId: '492985332872-he4ldbc04juiji114dnbgjc12tj8c4h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMaps',
  );
}
